modify gh actions to show success/fail

diff --git a/.github/workflows/basic_test_with_emodb_os_svm.yaml b/.github/workflows/basic_test_with_emodb_os_svm.yaml
--- a/.github/workflows/basic_test_with_emodb_os_svm.yaml
+++ b/.github/workflows/basic_test_with_emodb_os_svm.yaml
@@ -27,3 +27,9 @@ jobs:
     - name: Run tests
       run: |
         python3 -m nkululeko.nkululeko --config data/emodb/exp_os_svm.ini
+        if grep -q "DONE" output.txt; then
+          echo "Test Sucsess"
+        else
+          echo "Test Failed"
+          exit 1
+        fi
